// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualityApi.Data;

#nullable disable

namespace QualityApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241115015628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QualityApi.Cases.Entities.Case", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Outcome")
                        .HasColumnType("longtext");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("RecoveredCost")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("cases");
                });

            modelBuilder.Entity("QualityApi.Locations.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Aisle")
                        .HasColumnType("int");

                    b.Property<long?>("CaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullLocation")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Shelf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Aisle = 1,
                            FullLocation = "01-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 2L,
                            Aisle = 1,
                            FullLocation = "01-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 3L,
                            Aisle = 1,
                            FullLocation = "01-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 4L,
                            Aisle = 1,
                            FullLocation = "01-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 5L,
                            Aisle = 1,
                            FullLocation = "02-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 6L,
                            Aisle = 1,
                            FullLocation = "02-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 7L,
                            Aisle = 1,
                            FullLocation = "02-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 8L,
                            Aisle = 1,
                            FullLocation = "02-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 9L,
                            Aisle = 1,
                            FullLocation = "03-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 10L,
                            Aisle = 1,
                            FullLocation = "03-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 11L,
                            Aisle = 1,
                            FullLocation = "03-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 12L,
                            Aisle = 1,
                            FullLocation = "03-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 13L,
                            Aisle = 1,
                            FullLocation = "04-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 14L,
                            Aisle = 1,
                            FullLocation = "04-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 15L,
                            Aisle = 1,
                            FullLocation = "04-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 16L,
                            Aisle = 1,
                            FullLocation = "04-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 17L,
                            Aisle = 1,
                            FullLocation = "05-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 18L,
                            Aisle = 1,
                            FullLocation = "05-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 19L,
                            Aisle = 1,
                            FullLocation = "05-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 20L,
                            Aisle = 1,
                            FullLocation = "05-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 21L,
                            Aisle = 1,
                            FullLocation = "06-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 22L,
                            Aisle = 1,
                            FullLocation = "06-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 23L,
                            Aisle = 1,
                            FullLocation = "06-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 24L,
                            Aisle = 1,
                            FullLocation = "06-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 25L,
                            Aisle = 1,
                            FullLocation = "07-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 26L,
                            Aisle = 1,
                            FullLocation = "07-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 27L,
                            Aisle = 1,
                            FullLocation = "07-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 28L,
                            Aisle = 1,
                            FullLocation = "07-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 29L,
                            Aisle = 1,
                            FullLocation = "08-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 30L,
                            Aisle = 1,
                            FullLocation = "08-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 31L,
                            Aisle = 1,
                            FullLocation = "08-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 32L,
                            Aisle = 1,
                            FullLocation = "08-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 33L,
                            Aisle = 1,
                            FullLocation = "09-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 34L,
                            Aisle = 1,
                            FullLocation = "09-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 35L,
                            Aisle = 1,
                            FullLocation = "09-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 36L,
                            Aisle = 1,
                            FullLocation = "09-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 37L,
                            Aisle = 1,
                            FullLocation = "10-01-01",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 38L,
                            Aisle = 1,
                            FullLocation = "10-02-01",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 39L,
                            Aisle = 1,
                            FullLocation = "10-03-01",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 40L,
                            Aisle = 1,
                            FullLocation = "10-04-01",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 41L,
                            Aisle = 2,
                            FullLocation = "01-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 42L,
                            Aisle = 2,
                            FullLocation = "01-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 43L,
                            Aisle = 2,
                            FullLocation = "01-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 44L,
                            Aisle = 2,
                            FullLocation = "01-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 45L,
                            Aisle = 2,
                            FullLocation = "02-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 46L,
                            Aisle = 2,
                            FullLocation = "02-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 47L,
                            Aisle = 2,
                            FullLocation = "02-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 48L,
                            Aisle = 2,
                            FullLocation = "02-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 49L,
                            Aisle = 2,
                            FullLocation = "03-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 50L,
                            Aisle = 2,
                            FullLocation = "03-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 51L,
                            Aisle = 2,
                            FullLocation = "03-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 52L,
                            Aisle = 2,
                            FullLocation = "03-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 53L,
                            Aisle = 2,
                            FullLocation = "04-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 54L,
                            Aisle = 2,
                            FullLocation = "04-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 55L,
                            Aisle = 2,
                            FullLocation = "04-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 56L,
                            Aisle = 2,
                            FullLocation = "04-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 57L,
                            Aisle = 2,
                            FullLocation = "05-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 58L,
                            Aisle = 2,
                            FullLocation = "05-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 59L,
                            Aisle = 2,
                            FullLocation = "05-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 60L,
                            Aisle = 2,
                            FullLocation = "05-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 61L,
                            Aisle = 2,
                            FullLocation = "06-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 62L,
                            Aisle = 2,
                            FullLocation = "06-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 63L,
                            Aisle = 2,
                            FullLocation = "06-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 64L,
                            Aisle = 2,
                            FullLocation = "06-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 65L,
                            Aisle = 2,
                            FullLocation = "07-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 66L,
                            Aisle = 2,
                            FullLocation = "07-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 67L,
                            Aisle = 2,
                            FullLocation = "07-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 68L,
                            Aisle = 2,
                            FullLocation = "07-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 69L,
                            Aisle = 2,
                            FullLocation = "08-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 70L,
                            Aisle = 2,
                            FullLocation = "08-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 71L,
                            Aisle = 2,
                            FullLocation = "08-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 72L,
                            Aisle = 2,
                            FullLocation = "08-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 73L,
                            Aisle = 2,
                            FullLocation = "09-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 74L,
                            Aisle = 2,
                            FullLocation = "09-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 75L,
                            Aisle = 2,
                            FullLocation = "09-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 76L,
                            Aisle = 2,
                            FullLocation = "09-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 77L,
                            Aisle = 2,
                            FullLocation = "10-01-02",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 78L,
                            Aisle = 2,
                            FullLocation = "10-02-02",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 79L,
                            Aisle = 2,
                            FullLocation = "10-03-02",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 80L,
                            Aisle = 2,
                            FullLocation = "10-04-02",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 81L,
                            Aisle = 3,
                            FullLocation = "01-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 82L,
                            Aisle = 3,
                            FullLocation = "01-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 83L,
                            Aisle = 3,
                            FullLocation = "01-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 84L,
                            Aisle = 3,
                            FullLocation = "01-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 85L,
                            Aisle = 3,
                            FullLocation = "02-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 86L,
                            Aisle = 3,
                            FullLocation = "02-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 87L,
                            Aisle = 3,
                            FullLocation = "02-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 88L,
                            Aisle = 3,
                            FullLocation = "02-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 89L,
                            Aisle = 3,
                            FullLocation = "03-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 90L,
                            Aisle = 3,
                            FullLocation = "03-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 91L,
                            Aisle = 3,
                            FullLocation = "03-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 92L,
                            Aisle = 3,
                            FullLocation = "03-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 93L,
                            Aisle = 3,
                            FullLocation = "04-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 94L,
                            Aisle = 3,
                            FullLocation = "04-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 95L,
                            Aisle = 3,
                            FullLocation = "04-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 96L,
                            Aisle = 3,
                            FullLocation = "04-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 97L,
                            Aisle = 3,
                            FullLocation = "05-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 98L,
                            Aisle = 3,
                            FullLocation = "05-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 99L,
                            Aisle = 3,
                            FullLocation = "05-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 100L,
                            Aisle = 3,
                            FullLocation = "05-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 101L,
                            Aisle = 3,
                            FullLocation = "06-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 102L,
                            Aisle = 3,
                            FullLocation = "06-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 103L,
                            Aisle = 3,
                            FullLocation = "06-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 104L,
                            Aisle = 3,
                            FullLocation = "06-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 105L,
                            Aisle = 3,
                            FullLocation = "07-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 106L,
                            Aisle = 3,
                            FullLocation = "07-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 107L,
                            Aisle = 3,
                            FullLocation = "07-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 108L,
                            Aisle = 3,
                            FullLocation = "07-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 109L,
                            Aisle = 3,
                            FullLocation = "08-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 110L,
                            Aisle = 3,
                            FullLocation = "08-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 111L,
                            Aisle = 3,
                            FullLocation = "08-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 112L,
                            Aisle = 3,
                            FullLocation = "08-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 113L,
                            Aisle = 3,
                            FullLocation = "09-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 114L,
                            Aisle = 3,
                            FullLocation = "09-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 115L,
                            Aisle = 3,
                            FullLocation = "09-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 116L,
                            Aisle = 3,
                            FullLocation = "09-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 117L,
                            Aisle = 3,
                            FullLocation = "10-01-03",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 118L,
                            Aisle = 3,
                            FullLocation = "10-02-03",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 119L,
                            Aisle = 3,
                            FullLocation = "10-03-03",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 120L,
                            Aisle = 3,
                            FullLocation = "10-04-03",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 121L,
                            Aisle = 4,
                            FullLocation = "01-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 122L,
                            Aisle = 4,
                            FullLocation = "01-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 123L,
                            Aisle = 4,
                            FullLocation = "01-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 124L,
                            Aisle = 4,
                            FullLocation = "01-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 125L,
                            Aisle = 4,
                            FullLocation = "02-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 126L,
                            Aisle = 4,
                            FullLocation = "02-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 127L,
                            Aisle = 4,
                            FullLocation = "02-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 128L,
                            Aisle = 4,
                            FullLocation = "02-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 129L,
                            Aisle = 4,
                            FullLocation = "03-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 130L,
                            Aisle = 4,
                            FullLocation = "03-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 131L,
                            Aisle = 4,
                            FullLocation = "03-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 132L,
                            Aisle = 4,
                            FullLocation = "03-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 133L,
                            Aisle = 4,
                            FullLocation = "04-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 134L,
                            Aisle = 4,
                            FullLocation = "04-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 135L,
                            Aisle = 4,
                            FullLocation = "04-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 136L,
                            Aisle = 4,
                            FullLocation = "04-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 137L,
                            Aisle = 4,
                            FullLocation = "05-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 138L,
                            Aisle = 4,
                            FullLocation = "05-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 139L,
                            Aisle = 4,
                            FullLocation = "05-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 140L,
                            Aisle = 4,
                            FullLocation = "05-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 141L,
                            Aisle = 4,
                            FullLocation = "06-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 142L,
                            Aisle = 4,
                            FullLocation = "06-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 143L,
                            Aisle = 4,
                            FullLocation = "06-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 144L,
                            Aisle = 4,
                            FullLocation = "06-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 145L,
                            Aisle = 4,
                            FullLocation = "07-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 146L,
                            Aisle = 4,
                            FullLocation = "07-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 147L,
                            Aisle = 4,
                            FullLocation = "07-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 148L,
                            Aisle = 4,
                            FullLocation = "07-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 149L,
                            Aisle = 4,
                            FullLocation = "08-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 150L,
                            Aisle = 4,
                            FullLocation = "08-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 151L,
                            Aisle = 4,
                            FullLocation = "08-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 152L,
                            Aisle = 4,
                            FullLocation = "08-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 153L,
                            Aisle = 4,
                            FullLocation = "09-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 154L,
                            Aisle = 4,
                            FullLocation = "09-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 155L,
                            Aisle = 4,
                            FullLocation = "09-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 156L,
                            Aisle = 4,
                            FullLocation = "09-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 157L,
                            Aisle = 4,
                            FullLocation = "10-01-04",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 158L,
                            Aisle = 4,
                            FullLocation = "10-02-04",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 159L,
                            Aisle = 4,
                            FullLocation = "10-03-04",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 160L,
                            Aisle = 4,
                            FullLocation = "10-04-04",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 161L,
                            Aisle = 5,
                            FullLocation = "01-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 162L,
                            Aisle = 5,
                            FullLocation = "01-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 163L,
                            Aisle = 5,
                            FullLocation = "01-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 164L,
                            Aisle = 5,
                            FullLocation = "01-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 1
                        },
                        new
                        {
                            Id = 165L,
                            Aisle = 5,
                            FullLocation = "02-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 166L,
                            Aisle = 5,
                            FullLocation = "02-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 167L,
                            Aisle = 5,
                            FullLocation = "02-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 168L,
                            Aisle = 5,
                            FullLocation = "02-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 2
                        },
                        new
                        {
                            Id = 169L,
                            Aisle = 5,
                            FullLocation = "03-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 170L,
                            Aisle = 5,
                            FullLocation = "03-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 171L,
                            Aisle = 5,
                            FullLocation = "03-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 172L,
                            Aisle = 5,
                            FullLocation = "03-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 3
                        },
                        new
                        {
                            Id = 173L,
                            Aisle = 5,
                            FullLocation = "04-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 174L,
                            Aisle = 5,
                            FullLocation = "04-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 175L,
                            Aisle = 5,
                            FullLocation = "04-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 176L,
                            Aisle = 5,
                            FullLocation = "04-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 4
                        },
                        new
                        {
                            Id = 177L,
                            Aisle = 5,
                            FullLocation = "05-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 178L,
                            Aisle = 5,
                            FullLocation = "05-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 179L,
                            Aisle = 5,
                            FullLocation = "05-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 180L,
                            Aisle = 5,
                            FullLocation = "05-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 5
                        },
                        new
                        {
                            Id = 181L,
                            Aisle = 5,
                            FullLocation = "06-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 182L,
                            Aisle = 5,
                            FullLocation = "06-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 183L,
                            Aisle = 5,
                            FullLocation = "06-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 184L,
                            Aisle = 5,
                            FullLocation = "06-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 6
                        },
                        new
                        {
                            Id = 185L,
                            Aisle = 5,
                            FullLocation = "07-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 186L,
                            Aisle = 5,
                            FullLocation = "07-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 187L,
                            Aisle = 5,
                            FullLocation = "07-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 188L,
                            Aisle = 5,
                            FullLocation = "07-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 7
                        },
                        new
                        {
                            Id = 189L,
                            Aisle = 5,
                            FullLocation = "08-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 190L,
                            Aisle = 5,
                            FullLocation = "08-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 191L,
                            Aisle = 5,
                            FullLocation = "08-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 192L,
                            Aisle = 5,
                            FullLocation = "08-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 8
                        },
                        new
                        {
                            Id = 193L,
                            Aisle = 5,
                            FullLocation = "09-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 194L,
                            Aisle = 5,
                            FullLocation = "09-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 195L,
                            Aisle = 5,
                            FullLocation = "09-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 196L,
                            Aisle = 5,
                            FullLocation = "09-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 9
                        },
                        new
                        {
                            Id = 197L,
                            Aisle = 5,
                            FullLocation = "10-01-05",
                            IsOccupied = false,
                            Level = 1,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 198L,
                            Aisle = 5,
                            FullLocation = "10-02-05",
                            IsOccupied = false,
                            Level = 2,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 199L,
                            Aisle = 5,
                            FullLocation = "10-03-05",
                            IsOccupied = false,
                            Level = 3,
                            Shelf = 10
                        },
                        new
                        {
                            Id = 200L,
                            Aisle = 5,
                            FullLocation = "10-04-05",
                            IsOccupied = false,
                            Level = 4,
                            Shelf = 10
                        });
                });

            modelBuilder.Entity("QualityApi.Product.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("UnitWeight")
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("QualityApi.Cases.Entities.Case", b =>
                {
                    b.HasOne("QualityApi.Locations.Entities.Location", "Location")
                        .WithOne("Case")
                        .HasForeignKey("QualityApi.Cases.Entities.Case", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityApi.Product.Entities.Product", "Product")
                        .WithMany("Cases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QualityApi.Locations.Entities.Location", b =>
                {
                    b.Navigation("Case");
                });

            modelBuilder.Entity("QualityApi.Product.Entities.Product", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
